### ISSUE TITLE
AssertionError: LoRa initialization failed

### ISSUE THREAD

**Issue by janipewter** [martynwheeler/u-lora#11]
Hi, I am using RFM95 and when I try to run this code on Pi Pico it gives this error:

`Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "ulora.py", line 140, in __init__
AssertionError: LoRa initialization failed`

What am I doing wrong?

**Comment by Bicko** [comment]
Hi, I realise quite a bit of time has passed, but I'm getting the exact same error, with the same kit. Would love to know what's wrong.
I've checked the wiring may times. I'm using two RFM95 modules and two Picos, but get the same error. I suspect the RFM95 modules may be dead, but I don't know how to test this theory.

If anyone has any suggestions, please shout up! :-)

**Comment by hirdeshmewada** [comment]
i also have the same error

**Comment by ArmyTrained1974** [comment]
Why do I keep getting 
(((File "<stdin>", line 2, in <module> 
ImportError: no module named 'ulora.LoRa')))??? 
And what other things MUST be loaded onto the PICO and Linux Mint ( like SPI &/or SPIDEV, UCOLLECTIONS, PIPKIN -- AND MORE? I have tried about 4 months now to get this to work, still errors

@martywheeler Could you please look into this issue? Several of us are experiencing errors.

**Comment by ArmyTrained1974** [comment]
LONG BATTLE -- BUT IT WORKS !!
My physical setup is ONE LAPTOP using Two USB Ports, so CONFIGURE one on /dev/ttyACM0 and the other /dev/ttyACM1 using TWO separate instances of Thonny 3.10 and MICROPYTHON, not Circuitpython.

The ( __init__ ) was the breadboard !! Signals not getting from PICO to RFN95x.
(brand new, 1st time use)

Over FOUR MONTHS, but found / eliminated multiple problems.
1. they didn't tell us we HAD TO HAVE **Packages and Plug-ins** to make the program code to function. [ I am brand new to Python, etc. and didn't know anything ]
2. this code tells us to have all of the "import" bits, BUT YOU MUST FIND THEM ON GITHUB"
import time
import math
from ucollections import namedtuple   <<<<<<< (use 'collections'}
from urandom import getrandbits         <<<<<<< (use 'random')
from machine import SPI                      <<<<<<< ( use 'spi' and 'spidev')
from machine import Pin
3. DO NOT TRUST YOUR TEST STATION - I have 2 separate breadboards, put a PICO & RFM95x pair on each. After finally getting one set to work, but Not the 2nd, I went through Every Device on the 2nd Breadboard - never worked. 
FINALLY I tested the RFM95x's them on the "working model" - verified that They All Worked. Then moved to other pins on the breadboard -- ALL WORKED.


    SCK - This is the SPI Clock pin, its an input to the chip
    MISO - this is the Microcontroller In Serial Out pin, for data sent from the radio to your processor, 3.3V logic level
    MOSI - this is the Microcontroller Out Serial In pin, for data sent from your processor to the radio
    CS - this is the Chip Select pin, drop it low to start an SPI transaction. Its an input to the chip
    RST - this is the Reset pin for the radio. It's pulled high by default which is reset. Pull LOW to turn on the radio
    G0 - the radio's "GPIO 0" pin, also known as the IRQ pin, used for interrupt request notification from the radio to the microcontroller, 3.3V logic level

https://learn.adafruit.com/adafruit-rfm69hcw-and-rfm96-rfm95-rfm98-lora-packet-padio-breakouts/pinouts

Using the Marty Wheeler code and pinout 
https://github.com/martynwheeler/u-lora/tree/main/examples
Dronebot Workshop
https://www.youtube.com/watch?v=YQ7aLHCTeeE&t=2350s
          Physical Pin, not GPIO
CLK      09
RST      32
CS        07
INT       32
MOSI    10
MISO    06
GO        34
EN - not used b/c it is pulled high by RFM95x
